################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_attributes_read.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_attributes_set.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_create.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_default_get.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_default_get_copy.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_default_set.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_delete.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_entry_read.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_entry_write.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_exFAT_entry_read.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_exFAT_entry_write.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_exFAT_free_search.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_exFAT_unicode_entry_write.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_first_entry_find.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_first_full_entry_find.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_free_search.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_information_get.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_local_path_clear.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_local_path_get.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_local_path_get_copy.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_local_path_restore.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_local_path_set.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_long_name_get.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_long_name_get_extended.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_name_extract.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_name_test.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_next_entry_find.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_next_full_entry_find.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_rename.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_search.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_short_name_get.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_directory_short_name_get_extended.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_add_FAT_log.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_add_bitmap_log.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_add_checksum_log.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_add_dir_log.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_apply_logs.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_calculate_checksum.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_cleanup_FAT_chain.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_create_log_file.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_enable.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_read_FAT.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_read_directory_sector.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_read_log_file.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_recover.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_reset_log_file.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_set_FAT_chain.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_transaction_end.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_transaction_fail.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_transaction_start.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_write_log_file.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_file_allocate.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_file_attributes_read.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_file_attributes_set.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_file_best_effort_allocate.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_file_close.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_file_create.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_file_date_time_set.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_file_delete.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_file_extended_allocate.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_file_extended_best_effort_allocate.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_file_extended_relative_seek.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_file_extended_seek.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_file_extended_truncate.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_file_extended_truncate_release.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_file_open.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_file_read.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_file_relative_seek.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_file_rename.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_file_seek.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_file_truncate.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_file_truncate_release.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_file_write.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_file_write_notify_set.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_media_abort.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_media_boot_info_extract.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_media_cache_invalidate.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_media_check.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_media_check_FAT_chain_check.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_media_check_lost_cluster_check.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_media_close.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_media_close_notify_set.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_media_exFAT_format.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_media_extended_space_available.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_media_flush.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_media_format.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_media_format_oem_name_set.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_media_format_type_set.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_media_format_volume_id_set.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_media_open.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_media_open_notify_set.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_media_read.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_media_space_available.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_media_volume_get.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_media_volume_get_extended.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_media_volume_set.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_media_write.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_partition_offset_calculate.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_ram_driver.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_system_date_get.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_system_date_set.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_system_initialize.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_system_time_get.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_system_time_set.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_system_timer_entry.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_trace_event_insert.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_trace_event_update.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_trace_object_register.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_trace_object_unregister.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_unicode_directory_create.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_unicode_directory_entry_change.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_unicode_directory_entry_read.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_unicode_directory_rename.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_unicode_directory_search.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_unicode_file_create.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_unicode_file_rename.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_unicode_length_get.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_unicode_length_get_extended.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_unicode_name_get.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_unicode_name_get_extended.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_unicode_short_name_get.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_unicode_short_name_get_extended.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_16_unsigned_read.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_16_unsigned_write.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_32_unsigned_read.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_32_unsigned_write.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_64_unsigned_read.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_64_unsigned_write.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_FAT_entry_read.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_FAT_entry_write.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_FAT_flush.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_FAT_map_flush.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_FAT_sector_get.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_absolute_path_get.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_allocate_new_cluster.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_bitmap_cache_prepare.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_bitmap_cache_update.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_bitmap_flush.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_bitmap_free_cluster_find.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_bitmap_initialize.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_bitmap_start_sector_get.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_cluster_free.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_cluster_state_get.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_cluster_state_set.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_geometry_check.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_name_hash_get.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_size_calculate.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_system_area_checksum_verify.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_system_area_checksum_write.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_system_area_format.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_system_sector_write.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_unicode_name_hash_get.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_upcase_table.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_logical_sector_cache_entry_read.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_logical_sector_flush.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_logical_sector_read.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_logical_sector_write.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_memory_copy.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_memory_set.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_string_length_get.c \
../rza/microsoft/azure-rtos/filex/common/src/fx_utility_token_length_get.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_directory_attributes_read.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_directory_attributes_set.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_directory_create.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_directory_default_get.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_directory_default_get_copy.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_directory_default_set.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_directory_delete.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_directory_first_entry_find.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_directory_first_full_entry_find.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_directory_information_get.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_directory_local_path_clear.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_directory_local_path_get.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_directory_local_path_get_copy.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_directory_local_path_restore.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_directory_local_path_set.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_directory_long_name_get.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_directory_long_name_get_extended.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_directory_name_test.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_directory_next_entry_find.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_directory_next_full_entry_find.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_directory_rename.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_directory_short_name_get.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_directory_short_name_get_extended.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_fault_tolerant_enable.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_file_allocate.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_file_attributes_read.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_file_attributes_set.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_file_best_effort_allocate.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_file_close.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_file_create.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_file_date_time_set.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_file_delete.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_file_extended_allocate.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_file_extended_best_effort_allocate.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_file_extended_relative_seek.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_file_extended_seek.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_file_extended_truncate.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_file_extended_truncate_release.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_file_open.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_file_read.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_file_relative_seek.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_file_rename.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_file_seek.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_file_truncate.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_file_truncate_release.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_file_write.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_file_write_notify_set.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_media_abort.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_media_cache_invalidate.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_media_check.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_media_close.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_media_close_notify_set.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_media_exFAT_format.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_media_extended_space_available.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_media_flush.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_media_format.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_media_open.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_media_open_notify_set.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_media_read.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_media_space_available.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_media_volume_get.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_media_volume_get_extended.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_media_volume_set.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_media_write.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_system_date_get.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_system_date_set.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_system_time_get.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_system_time_set.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_unicode_directory_create.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_unicode_directory_rename.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_unicode_file_create.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_unicode_file_rename.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_unicode_name_get.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_unicode_name_get_extended.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_unicode_short_name_get.c \
../rza/microsoft/azure-rtos/filex/common/src/fxe_unicode_short_name_get_extended.c 

LST += \
fx_directory_attributes_read.lst \
fx_directory_attributes_set.lst \
fx_directory_create.lst \
fx_directory_default_get.lst \
fx_directory_default_get_copy.lst \
fx_directory_default_set.lst \
fx_directory_delete.lst \
fx_directory_entry_read.lst \
fx_directory_entry_write.lst \
fx_directory_exFAT_entry_read.lst \
fx_directory_exFAT_entry_write.lst \
fx_directory_exFAT_free_search.lst \
fx_directory_exFAT_unicode_entry_write.lst \
fx_directory_first_entry_find.lst \
fx_directory_first_full_entry_find.lst \
fx_directory_free_search.lst \
fx_directory_information_get.lst \
fx_directory_local_path_clear.lst \
fx_directory_local_path_get.lst \
fx_directory_local_path_get_copy.lst \
fx_directory_local_path_restore.lst \
fx_directory_local_path_set.lst \
fx_directory_long_name_get.lst \
fx_directory_long_name_get_extended.lst \
fx_directory_name_extract.lst \
fx_directory_name_test.lst \
fx_directory_next_entry_find.lst \
fx_directory_next_full_entry_find.lst \
fx_directory_rename.lst \
fx_directory_search.lst \
fx_directory_short_name_get.lst \
fx_directory_short_name_get_extended.lst \
fx_fault_tolerant_add_FAT_log.lst \
fx_fault_tolerant_add_bitmap_log.lst \
fx_fault_tolerant_add_checksum_log.lst \
fx_fault_tolerant_add_dir_log.lst \
fx_fault_tolerant_apply_logs.lst \
fx_fault_tolerant_calculate_checksum.lst \
fx_fault_tolerant_cleanup_FAT_chain.lst \
fx_fault_tolerant_create_log_file.lst \
fx_fault_tolerant_enable.lst \
fx_fault_tolerant_read_FAT.lst \
fx_fault_tolerant_read_directory_sector.lst \
fx_fault_tolerant_read_log_file.lst \
fx_fault_tolerant_recover.lst \
fx_fault_tolerant_reset_log_file.lst \
fx_fault_tolerant_set_FAT_chain.lst \
fx_fault_tolerant_transaction_end.lst \
fx_fault_tolerant_transaction_fail.lst \
fx_fault_tolerant_transaction_start.lst \
fx_fault_tolerant_write_log_file.lst \
fx_file_allocate.lst \
fx_file_attributes_read.lst \
fx_file_attributes_set.lst \
fx_file_best_effort_allocate.lst \
fx_file_close.lst \
fx_file_create.lst \
fx_file_date_time_set.lst \
fx_file_delete.lst \
fx_file_extended_allocate.lst \
fx_file_extended_best_effort_allocate.lst \
fx_file_extended_relative_seek.lst \
fx_file_extended_seek.lst \
fx_file_extended_truncate.lst \
fx_file_extended_truncate_release.lst \
fx_file_open.lst \
fx_file_read.lst \
fx_file_relative_seek.lst \
fx_file_rename.lst \
fx_file_seek.lst \
fx_file_truncate.lst \
fx_file_truncate_release.lst \
fx_file_write.lst \
fx_file_write_notify_set.lst \
fx_media_abort.lst \
fx_media_boot_info_extract.lst \
fx_media_cache_invalidate.lst \
fx_media_check.lst \
fx_media_check_FAT_chain_check.lst \
fx_media_check_lost_cluster_check.lst \
fx_media_close.lst \
fx_media_close_notify_set.lst \
fx_media_exFAT_format.lst \
fx_media_extended_space_available.lst \
fx_media_flush.lst \
fx_media_format.lst \
fx_media_format_oem_name_set.lst \
fx_media_format_type_set.lst \
fx_media_format_volume_id_set.lst \
fx_media_open.lst \
fx_media_open_notify_set.lst \
fx_media_read.lst \
fx_media_space_available.lst \
fx_media_volume_get.lst \
fx_media_volume_get_extended.lst \
fx_media_volume_set.lst \
fx_media_write.lst \
fx_partition_offset_calculate.lst \
fx_ram_driver.lst \
fx_system_date_get.lst \
fx_system_date_set.lst \
fx_system_initialize.lst \
fx_system_time_get.lst \
fx_system_time_set.lst \
fx_system_timer_entry.lst \
fx_trace_event_insert.lst \
fx_trace_event_update.lst \
fx_trace_object_register.lst \
fx_trace_object_unregister.lst \
fx_unicode_directory_create.lst \
fx_unicode_directory_entry_change.lst \
fx_unicode_directory_entry_read.lst \
fx_unicode_directory_rename.lst \
fx_unicode_directory_search.lst \
fx_unicode_file_create.lst \
fx_unicode_file_rename.lst \
fx_unicode_length_get.lst \
fx_unicode_length_get_extended.lst \
fx_unicode_name_get.lst \
fx_unicode_name_get_extended.lst \
fx_unicode_short_name_get.lst \
fx_unicode_short_name_get_extended.lst \
fx_utility_16_unsigned_read.lst \
fx_utility_16_unsigned_write.lst \
fx_utility_32_unsigned_read.lst \
fx_utility_32_unsigned_write.lst \
fx_utility_64_unsigned_read.lst \
fx_utility_64_unsigned_write.lst \
fx_utility_FAT_entry_read.lst \
fx_utility_FAT_entry_write.lst \
fx_utility_FAT_flush.lst \
fx_utility_FAT_map_flush.lst \
fx_utility_FAT_sector_get.lst \
fx_utility_absolute_path_get.lst \
fx_utility_exFAT_allocate_new_cluster.lst \
fx_utility_exFAT_bitmap_cache_prepare.lst \
fx_utility_exFAT_bitmap_cache_update.lst \
fx_utility_exFAT_bitmap_flush.lst \
fx_utility_exFAT_bitmap_free_cluster_find.lst \
fx_utility_exFAT_bitmap_initialize.lst \
fx_utility_exFAT_bitmap_start_sector_get.lst \
fx_utility_exFAT_cluster_free.lst \
fx_utility_exFAT_cluster_state_get.lst \
fx_utility_exFAT_cluster_state_set.lst \
fx_utility_exFAT_geometry_check.lst \
fx_utility_exFAT_name_hash_get.lst \
fx_utility_exFAT_size_calculate.lst \
fx_utility_exFAT_system_area_checksum_verify.lst \
fx_utility_exFAT_system_area_checksum_write.lst \
fx_utility_exFAT_system_area_format.lst \
fx_utility_exFAT_system_sector_write.lst \
fx_utility_exFAT_unicode_name_hash_get.lst \
fx_utility_exFAT_upcase_table.lst \
fx_utility_logical_sector_cache_entry_read.lst \
fx_utility_logical_sector_flush.lst \
fx_utility_logical_sector_read.lst \
fx_utility_logical_sector_write.lst \
fx_utility_memory_copy.lst \
fx_utility_memory_set.lst \
fx_utility_string_length_get.lst \
fx_utility_token_length_get.lst \
fxe_directory_attributes_read.lst \
fxe_directory_attributes_set.lst \
fxe_directory_create.lst \
fxe_directory_default_get.lst \
fxe_directory_default_get_copy.lst \
fxe_directory_default_set.lst \
fxe_directory_delete.lst \
fxe_directory_first_entry_find.lst \
fxe_directory_first_full_entry_find.lst \
fxe_directory_information_get.lst \
fxe_directory_local_path_clear.lst \
fxe_directory_local_path_get.lst \
fxe_directory_local_path_get_copy.lst \
fxe_directory_local_path_restore.lst \
fxe_directory_local_path_set.lst \
fxe_directory_long_name_get.lst \
fxe_directory_long_name_get_extended.lst \
fxe_directory_name_test.lst \
fxe_directory_next_entry_find.lst \
fxe_directory_next_full_entry_find.lst \
fxe_directory_rename.lst \
fxe_directory_short_name_get.lst \
fxe_directory_short_name_get_extended.lst \
fxe_fault_tolerant_enable.lst \
fxe_file_allocate.lst \
fxe_file_attributes_read.lst \
fxe_file_attributes_set.lst \
fxe_file_best_effort_allocate.lst \
fxe_file_close.lst \
fxe_file_create.lst \
fxe_file_date_time_set.lst \
fxe_file_delete.lst \
fxe_file_extended_allocate.lst \
fxe_file_extended_best_effort_allocate.lst \
fxe_file_extended_relative_seek.lst \
fxe_file_extended_seek.lst \
fxe_file_extended_truncate.lst \
fxe_file_extended_truncate_release.lst \
fxe_file_open.lst \
fxe_file_read.lst \
fxe_file_relative_seek.lst \
fxe_file_rename.lst \
fxe_file_seek.lst \
fxe_file_truncate.lst \
fxe_file_truncate_release.lst \
fxe_file_write.lst \
fxe_file_write_notify_set.lst \
fxe_media_abort.lst \
fxe_media_cache_invalidate.lst \
fxe_media_check.lst \
fxe_media_close.lst \
fxe_media_close_notify_set.lst \
fxe_media_exFAT_format.lst \
fxe_media_extended_space_available.lst \
fxe_media_flush.lst \
fxe_media_format.lst \
fxe_media_open.lst \
fxe_media_open_notify_set.lst \
fxe_media_read.lst \
fxe_media_space_available.lst \
fxe_media_volume_get.lst \
fxe_media_volume_get_extended.lst \
fxe_media_volume_set.lst \
fxe_media_write.lst \
fxe_system_date_get.lst \
fxe_system_date_set.lst \
fxe_system_time_get.lst \
fxe_system_time_set.lst \
fxe_unicode_directory_create.lst \
fxe_unicode_directory_rename.lst \
fxe_unicode_file_create.lst \
fxe_unicode_file_rename.lst \
fxe_unicode_name_get.lst \
fxe_unicode_name_get_extended.lst \
fxe_unicode_short_name_get.lst \
fxe_unicode_short_name_get_extended.lst 

C_DEPS += \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_attributes_read.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_attributes_set.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_create.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_default_get.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_default_get_copy.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_default_set.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_delete.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_entry_read.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_entry_write.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_exFAT_entry_read.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_exFAT_entry_write.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_exFAT_free_search.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_exFAT_unicode_entry_write.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_first_entry_find.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_first_full_entry_find.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_free_search.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_information_get.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_local_path_clear.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_local_path_get.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_local_path_get_copy.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_local_path_restore.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_local_path_set.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_long_name_get.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_long_name_get_extended.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_name_extract.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_name_test.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_next_entry_find.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_next_full_entry_find.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_rename.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_search.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_short_name_get.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_short_name_get_extended.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_add_FAT_log.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_add_bitmap_log.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_add_checksum_log.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_add_dir_log.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_apply_logs.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_calculate_checksum.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_cleanup_FAT_chain.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_create_log_file.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_enable.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_read_FAT.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_read_directory_sector.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_read_log_file.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_recover.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_reset_log_file.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_set_FAT_chain.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_transaction_end.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_transaction_fail.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_transaction_start.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_write_log_file.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_allocate.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_attributes_read.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_attributes_set.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_best_effort_allocate.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_close.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_create.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_date_time_set.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_delete.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_extended_allocate.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_extended_best_effort_allocate.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_extended_relative_seek.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_extended_seek.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_extended_truncate.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_extended_truncate_release.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_open.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_read.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_relative_seek.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_rename.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_seek.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_truncate.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_truncate_release.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_write.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_write_notify_set.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_abort.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_boot_info_extract.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_cache_invalidate.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_check.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_check_FAT_chain_check.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_check_lost_cluster_check.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_close.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_close_notify_set.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_exFAT_format.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_extended_space_available.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_flush.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_format.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_format_oem_name_set.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_format_type_set.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_format_volume_id_set.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_open.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_open_notify_set.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_read.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_space_available.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_volume_get.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_volume_get_extended.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_volume_set.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_write.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_partition_offset_calculate.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_ram_driver.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_system_date_get.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_system_date_set.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_system_initialize.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_system_time_get.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_system_time_set.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_system_timer_entry.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_trace_event_insert.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_trace_event_update.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_trace_object_register.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_trace_object_unregister.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_unicode_directory_create.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_unicode_directory_entry_change.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_unicode_directory_entry_read.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_unicode_directory_rename.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_unicode_directory_search.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_unicode_file_create.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_unicode_file_rename.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_unicode_length_get.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_unicode_length_get_extended.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_unicode_name_get.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_unicode_name_get_extended.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_unicode_short_name_get.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_unicode_short_name_get_extended.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_16_unsigned_read.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_16_unsigned_write.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_32_unsigned_read.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_32_unsigned_write.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_64_unsigned_read.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_64_unsigned_write.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_FAT_entry_read.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_FAT_entry_write.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_FAT_flush.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_FAT_map_flush.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_FAT_sector_get.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_absolute_path_get.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_allocate_new_cluster.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_bitmap_cache_prepare.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_bitmap_cache_update.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_bitmap_flush.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_bitmap_free_cluster_find.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_bitmap_initialize.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_bitmap_start_sector_get.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_cluster_free.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_cluster_state_get.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_cluster_state_set.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_geometry_check.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_name_hash_get.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_size_calculate.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_system_area_checksum_verify.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_system_area_checksum_write.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_system_area_format.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_system_sector_write.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_unicode_name_hash_get.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_upcase_table.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_logical_sector_cache_entry_read.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_logical_sector_flush.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_logical_sector_read.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_logical_sector_write.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_memory_copy.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_memory_set.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_string_length_get.d \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_token_length_get.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_attributes_read.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_attributes_set.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_create.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_default_get.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_default_get_copy.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_default_set.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_delete.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_first_entry_find.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_first_full_entry_find.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_information_get.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_local_path_clear.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_local_path_get.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_local_path_get_copy.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_local_path_restore.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_local_path_set.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_long_name_get.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_long_name_get_extended.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_name_test.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_next_entry_find.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_next_full_entry_find.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_rename.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_short_name_get.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_short_name_get_extended.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_fault_tolerant_enable.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_allocate.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_attributes_read.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_attributes_set.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_best_effort_allocate.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_close.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_create.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_date_time_set.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_delete.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_extended_allocate.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_extended_best_effort_allocate.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_extended_relative_seek.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_extended_seek.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_extended_truncate.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_extended_truncate_release.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_open.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_read.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_relative_seek.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_rename.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_seek.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_truncate.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_truncate_release.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_write.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_write_notify_set.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_abort.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_cache_invalidate.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_check.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_close.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_close_notify_set.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_exFAT_format.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_extended_space_available.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_flush.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_format.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_open.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_open_notify_set.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_read.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_space_available.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_volume_get.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_volume_get_extended.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_volume_set.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_write.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_system_date_get.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_system_date_set.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_system_time_get.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_system_time_set.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_unicode_directory_create.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_unicode_directory_rename.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_unicode_file_create.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_unicode_file_rename.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_unicode_name_get.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_unicode_name_get_extended.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_unicode_short_name_get.d \
./rza/microsoft/azure-rtos/filex/common/src/fxe_unicode_short_name_get_extended.d 

OBJS += \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_attributes_read.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_attributes_set.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_create.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_default_get.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_default_get_copy.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_default_set.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_delete.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_entry_read.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_entry_write.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_exFAT_entry_read.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_exFAT_entry_write.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_exFAT_free_search.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_exFAT_unicode_entry_write.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_first_entry_find.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_first_full_entry_find.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_free_search.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_information_get.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_local_path_clear.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_local_path_get.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_local_path_get_copy.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_local_path_restore.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_local_path_set.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_long_name_get.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_long_name_get_extended.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_name_extract.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_name_test.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_next_entry_find.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_next_full_entry_find.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_rename.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_search.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_short_name_get.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_directory_short_name_get_extended.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_add_FAT_log.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_add_bitmap_log.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_add_checksum_log.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_add_dir_log.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_apply_logs.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_calculate_checksum.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_cleanup_FAT_chain.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_create_log_file.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_enable.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_read_FAT.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_read_directory_sector.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_read_log_file.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_recover.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_reset_log_file.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_set_FAT_chain.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_transaction_end.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_transaction_fail.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_transaction_start.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_fault_tolerant_write_log_file.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_allocate.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_attributes_read.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_attributes_set.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_best_effort_allocate.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_close.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_create.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_date_time_set.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_delete.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_extended_allocate.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_extended_best_effort_allocate.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_extended_relative_seek.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_extended_seek.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_extended_truncate.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_extended_truncate_release.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_open.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_read.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_relative_seek.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_rename.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_seek.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_truncate.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_truncate_release.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_write.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_file_write_notify_set.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_abort.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_boot_info_extract.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_cache_invalidate.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_check.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_check_FAT_chain_check.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_check_lost_cluster_check.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_close.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_close_notify_set.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_exFAT_format.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_extended_space_available.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_flush.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_format.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_format_oem_name_set.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_format_type_set.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_format_volume_id_set.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_open.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_open_notify_set.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_read.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_space_available.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_volume_get.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_volume_get_extended.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_volume_set.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_media_write.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_partition_offset_calculate.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_ram_driver.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_system_date_get.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_system_date_set.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_system_initialize.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_system_time_get.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_system_time_set.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_system_timer_entry.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_trace_event_insert.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_trace_event_update.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_trace_object_register.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_trace_object_unregister.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_unicode_directory_create.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_unicode_directory_entry_change.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_unicode_directory_entry_read.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_unicode_directory_rename.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_unicode_directory_search.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_unicode_file_create.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_unicode_file_rename.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_unicode_length_get.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_unicode_length_get_extended.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_unicode_name_get.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_unicode_name_get_extended.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_unicode_short_name_get.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_unicode_short_name_get_extended.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_16_unsigned_read.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_16_unsigned_write.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_32_unsigned_read.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_32_unsigned_write.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_64_unsigned_read.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_64_unsigned_write.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_FAT_entry_read.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_FAT_entry_write.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_FAT_flush.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_FAT_map_flush.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_FAT_sector_get.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_absolute_path_get.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_allocate_new_cluster.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_bitmap_cache_prepare.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_bitmap_cache_update.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_bitmap_flush.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_bitmap_free_cluster_find.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_bitmap_initialize.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_bitmap_start_sector_get.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_cluster_free.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_cluster_state_get.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_cluster_state_set.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_geometry_check.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_name_hash_get.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_size_calculate.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_system_area_checksum_verify.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_system_area_checksum_write.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_system_area_format.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_system_sector_write.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_unicode_name_hash_get.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_exFAT_upcase_table.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_logical_sector_cache_entry_read.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_logical_sector_flush.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_logical_sector_read.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_logical_sector_write.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_memory_copy.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_memory_set.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_string_length_get.o \
./rza/microsoft/azure-rtos/filex/common/src/fx_utility_token_length_get.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_attributes_read.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_attributes_set.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_create.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_default_get.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_default_get_copy.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_default_set.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_delete.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_first_entry_find.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_first_full_entry_find.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_information_get.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_local_path_clear.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_local_path_get.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_local_path_get_copy.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_local_path_restore.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_local_path_set.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_long_name_get.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_long_name_get_extended.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_name_test.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_next_entry_find.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_next_full_entry_find.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_rename.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_short_name_get.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_directory_short_name_get_extended.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_fault_tolerant_enable.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_allocate.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_attributes_read.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_attributes_set.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_best_effort_allocate.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_close.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_create.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_date_time_set.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_delete.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_extended_allocate.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_extended_best_effort_allocate.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_extended_relative_seek.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_extended_seek.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_extended_truncate.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_extended_truncate_release.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_open.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_read.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_relative_seek.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_rename.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_seek.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_truncate.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_truncate_release.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_write.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_file_write_notify_set.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_abort.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_cache_invalidate.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_check.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_close.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_close_notify_set.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_exFAT_format.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_extended_space_available.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_flush.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_format.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_open.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_open_notify_set.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_read.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_space_available.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_volume_get.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_volume_get_extended.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_volume_set.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_media_write.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_system_date_get.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_system_date_set.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_system_time_get.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_system_time_set.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_unicode_directory_create.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_unicode_directory_rename.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_unicode_file_create.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_unicode_file_rename.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_unicode_name_get.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_unicode_name_get_extended.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_unicode_short_name_get.o \
./rza/microsoft/azure-rtos/filex/common/src/fxe_unicode_short_name_get_extended.o 

MAP += \
netx_demo_http_server_rza3_fsp.map 


# Each subdirectory must supply rules for building sources it contributes
rza/microsoft/azure-rtos/filex/common/src/%.o: ../rza/microsoft/azure-rtos/filex/common/src/%.c
	@echo 'Building file: $<'
	$(file > $@.in,-mcpu=cortex-a55 -mcmodel=large -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wunused -Wuninitialized -Wall -Wextra -Wmissing-declarations -Wconversion -Wpointer-arith -Wshadow -Wlogical-op -Waggregate-return -Wfloat-equal -g -gdwarf-4 -D_RZA_CORE=CA55_0 -D_RENESAS_RZA_ -D_RZA_ORDINAL=1 -I"C:/Users/ebob/e2_studio/workspace/netx_demo_http_server_rza3_fsp/generate" -I"C:/Users/ebob/e2_studio/workspace/netx_demo_http_server_rza3_fsp/src" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\src" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza\\fsp\\inc" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza\\fsp\\inc\\api" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza\\fsp\\inc\\instances" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza\\fsp\\src\\rm_threadx_port" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza\\microsoft\\azure-rtos\\threadx\\common\\inc" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza\\fsp\\src\\bsp\\mcu\\rza3ul" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza_gen" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza_cfg\\fsp_cfg\\bsp" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza_cfg\\fsp_cfg" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza_cfg\\fsp_cfg\\azure\\tx" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza_cfg\\fsp_cfg\\middleware" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza\\microsoft\\azure-rtos\\netxduo\\addons\\pop3" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza\\microsoft\\azure-rtos\\netxduo\\addons\\snmp" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza\\microsoft\\azure-rtos\\netxduo\\addons\\nat" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza\\microsoft\\azure-rtos\\netxduo\\addons\\mqtt" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza\\microsoft\\azure-rtos\\netxduo\\addons\\ftp" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza\\microsoft\\azure-rtos\\netxduo\\addons\\tftp" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza\\microsoft\\azure-rtos\\netxduo\\addons\\sntp" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza\\microsoft\\azure-rtos\\netxduo\\addons\\smtp" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza\\microsoft\\azure-rtos\\netxduo\\addons\\web" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza\\microsoft\\azure-rtos\\netxduo\\addons\\auto_ip" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza\\microsoft\\azure-rtos\\netxduo\\addons\\telnet" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza\\microsoft\\azure-rtos\\netxduo\\addons\\dns" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza\\microsoft\\azure-rtos\\netxduo\\addons\\dhcp" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza\\microsoft\\azure-rtos\\netxduo\\addons\\http" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza\\microsoft\\azure-rtos\\netxduo\\common\\inc" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza\\microsoft\\azure-rtos\\netxduo\\addons\\cloud" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza\\fsp\\src\\rm_netxduo_ether" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza_cfg\\fsp_cfg\\azure\\nxd" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza\\fsp\\inc\\ports" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza\\microsoft\\azure-rtos\\filex\\common\\inc" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza_cfg\\fsp_cfg\\azure\\fx" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza_cfg\\rza_gen" -I"C:\\Users\\ebob\\e2_studio\\workspace\\netx_demo_http_server_rza3_fsp\\rza_cfg\\driver" -I"." -std=c99 -w -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<")
	@aarch64-none-elf-gcc @"$@.in"

