################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
SX_SRCS := 
LINKER_SCRIPT := 
JMP_UPPER_SRCS := 
P_UPPER_SRCS := 
SRC_SRCS := 
JMP_SRCS := 
FSY_UPPER_SRCS := 
PP_UPPER_SRCS := 
OBJ_UPPER_SRCS := 
ASM_SRCS := 
SX_UPPER_SRCS := 
O_UPPER_SRCS := 
S_UPPER_SRCS := 
ELF_UPPER_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
S_SRCS := 
PP_SRCS := 
SRC_UPPER_SRCS := 
FSY_SRCS := 
P_SRCS := 
C_SRCS := 
JMP_DEPS := 
FSY_DEPS := 
C_UPPER_DEPS := 
SECONDARY_SIZE := 
SRC_UPPER_DEPS := 
P_UPPER_DEPS := 
S_DEPS := 
LST := 
PP_UPPER_DEPS := 
P_DEPS := 
FSY_UPPER_DEPS := 
C_DEPS := 
SRC_DEPS := 
JMP_UPPER_DEPS := 
PP_DEPS := 
SX_DEPS := 
ASM_UPPER_DEPS := 
SX_UPPER_DEPS := 
OBJS := 
SECONDARY_FLASH := 
ASM_DEPS := 
S_UPPER_DEPS := 
MAP := 

# Every subdirectory with source files must be described here
SUBDIRS := \
rza/board/rza3ul_smarc_qspi \
rza/fsp/src/bsp/cmsis/Device/RENESAS/Source \
rza/fsp/src/bsp/mcu/all \
rza/fsp/src/bsp/mcu/rza3ul \
rza/fsp/src/r_gether \
rza/fsp/src/r_gether_phy \
rza/fsp/src/r_gether_phy/targets/KSZ9131RNXI \
rza/fsp/src/r_gtm \
rza/fsp/src/r_ioport \
rza/fsp/src/r_mmu \
rza/fsp/src/r_scif_uart \
rza/fsp/src/r_sdhi \
rza/fsp/src/rm_block_media_sdmmc \
rza/fsp/src/rm_filex_block_media \
rza/fsp/src/rm_netxduo_ether \
rza/fsp/src/rm_threadx_port \
rza/microsoft/azure-rtos/filex/common/src \
rza/microsoft/azure-rtos/netxduo/addons/auto_ip \
rza/microsoft/azure-rtos/netxduo/addons/cloud \
rza/microsoft/azure-rtos/netxduo/addons/dhcp \
rza/microsoft/azure-rtos/netxduo/addons/dns \
rza/microsoft/azure-rtos/netxduo/addons/ftp \
rza/microsoft/azure-rtos/netxduo/addons/http \
rza/microsoft/azure-rtos/netxduo/addons/mqtt \
rza/microsoft/azure-rtos/netxduo/addons/nat \
rza/microsoft/azure-rtos/netxduo/addons/pop3 \
rza/microsoft/azure-rtos/netxduo/addons/smtp \
rza/microsoft/azure-rtos/netxduo/addons/snmp \
rza/microsoft/azure-rtos/netxduo/addons/sntp \
rza/microsoft/azure-rtos/netxduo/addons/telnet \
rza/microsoft/azure-rtos/netxduo/addons/tftp \
rza/microsoft/azure-rtos/netxduo/addons/web \
rza/microsoft/azure-rtos/netxduo/common/src \
rza/microsoft/azure-rtos/threadx/common/src \
rza_gen \
src \

