################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../rza/microsoft/azure-rtos/threadx/common/src/tx_block_allocate.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_block_pool_cleanup.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_block_pool_create.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_block_pool_delete.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_block_pool_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_block_pool_initialize.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_block_pool_performance_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_block_pool_performance_system_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_block_pool_prioritize.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_block_release.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_byte_allocate.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_cleanup.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_create.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_delete.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_initialize.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_performance_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_performance_system_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_prioritize.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_search.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_byte_release.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_event_flags_cleanup.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_event_flags_create.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_event_flags_delete.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_event_flags_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_event_flags_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_event_flags_initialize.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_event_flags_performance_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_event_flags_performance_system_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_event_flags_set.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_event_flags_set_notify.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_initialize_high_level.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_initialize_kernel_enter.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_initialize_kernel_setup.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_cleanup.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_create.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_delete.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_initialize.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_performance_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_performance_system_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_prioritize.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_priority_change.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_put.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_queue_cleanup.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_queue_create.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_queue_delete.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_queue_flush.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_queue_front_send.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_queue_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_queue_initialize.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_queue_performance_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_queue_performance_system_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_queue_prioritize.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_queue_receive.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_queue_send.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_queue_send_notify.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_ceiling_put.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_cleanup.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_create.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_delete.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_initialize.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_performance_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_performance_system_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_prioritize.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_put.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_put_notify.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_thread_create.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_thread_delete.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_thread_entry_exit_notify.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_thread_identify.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_thread_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_thread_initialize.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_thread_performance_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_thread_performance_system_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_thread_preemption_change.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_thread_priority_change.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_thread_relinquish.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_thread_reset.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_thread_resume.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_thread_shell_entry.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_thread_sleep.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_thread_stack_analyze.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_thread_stack_error_handler.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_thread_stack_error_notify.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_thread_suspend.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_thread_system_preempt_check.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_thread_system_resume.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_thread_system_suspend.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_thread_terminate.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_thread_time_slice.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_thread_time_slice_change.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_thread_timeout.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_thread_wait_abort.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_time_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_time_set.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_timer_activate.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_timer_change.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_timer_create.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_timer_deactivate.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_timer_delete.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_timer_expiration_process.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_timer_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_timer_initialize.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_timer_performance_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_timer_performance_system_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_timer_system_activate.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_timer_system_deactivate.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_timer_thread_entry.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_trace_buffer_full_notify.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_trace_disable.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_trace_enable.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_trace_event_filter.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_trace_event_unfilter.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_trace_initialize.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_trace_interrupt_control.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_trace_isr_enter_insert.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_trace_isr_exit_insert.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_trace_object_register.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_trace_object_unregister.c \
../rza/microsoft/azure-rtos/threadx/common/src/tx_trace_user_event_insert.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_block_allocate.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_block_pool_create.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_block_pool_delete.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_block_pool_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_block_pool_prioritize.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_block_release.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_byte_allocate.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_byte_pool_create.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_byte_pool_delete.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_byte_pool_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_byte_pool_prioritize.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_byte_release.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_event_flags_create.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_event_flags_delete.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_event_flags_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_event_flags_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_event_flags_set.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_event_flags_set_notify.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_mutex_create.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_mutex_delete.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_mutex_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_mutex_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_mutex_prioritize.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_mutex_put.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_queue_create.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_queue_delete.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_queue_flush.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_queue_front_send.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_queue_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_queue_prioritize.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_queue_receive.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_queue_send.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_queue_send_notify.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_semaphore_ceiling_put.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_semaphore_create.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_semaphore_delete.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_semaphore_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_semaphore_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_semaphore_prioritize.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_semaphore_put.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_semaphore_put_notify.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_thread_create.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_thread_delete.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_thread_entry_exit_notify.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_thread_info_get.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_thread_preemption_change.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_thread_priority_change.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_thread_relinquish.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_thread_reset.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_thread_resume.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_thread_suspend.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_thread_terminate.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_thread_time_slice_change.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_thread_wait_abort.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_timer_activate.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_timer_change.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_timer_create.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_timer_deactivate.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_timer_delete.c \
../rza/microsoft/azure-rtos/threadx/common/src/txe_timer_info_get.c 

LST += \
tx_block_allocate.lst \
tx_block_pool_cleanup.lst \
tx_block_pool_create.lst \
tx_block_pool_delete.lst \
tx_block_pool_info_get.lst \
tx_block_pool_initialize.lst \
tx_block_pool_performance_info_get.lst \
tx_block_pool_performance_system_info_get.lst \
tx_block_pool_prioritize.lst \
tx_block_release.lst \
tx_byte_allocate.lst \
tx_byte_pool_cleanup.lst \
tx_byte_pool_create.lst \
tx_byte_pool_delete.lst \
tx_byte_pool_info_get.lst \
tx_byte_pool_initialize.lst \
tx_byte_pool_performance_info_get.lst \
tx_byte_pool_performance_system_info_get.lst \
tx_byte_pool_prioritize.lst \
tx_byte_pool_search.lst \
tx_byte_release.lst \
tx_event_flags_cleanup.lst \
tx_event_flags_create.lst \
tx_event_flags_delete.lst \
tx_event_flags_get.lst \
tx_event_flags_info_get.lst \
tx_event_flags_initialize.lst \
tx_event_flags_performance_info_get.lst \
tx_event_flags_performance_system_info_get.lst \
tx_event_flags_set.lst \
tx_event_flags_set_notify.lst \
tx_initialize_high_level.lst \
tx_initialize_kernel_enter.lst \
tx_initialize_kernel_setup.lst \
tx_mutex_cleanup.lst \
tx_mutex_create.lst \
tx_mutex_delete.lst \
tx_mutex_get.lst \
tx_mutex_info_get.lst \
tx_mutex_initialize.lst \
tx_mutex_performance_info_get.lst \
tx_mutex_performance_system_info_get.lst \
tx_mutex_prioritize.lst \
tx_mutex_priority_change.lst \
tx_mutex_put.lst \
tx_queue_cleanup.lst \
tx_queue_create.lst \
tx_queue_delete.lst \
tx_queue_flush.lst \
tx_queue_front_send.lst \
tx_queue_info_get.lst \
tx_queue_initialize.lst \
tx_queue_performance_info_get.lst \
tx_queue_performance_system_info_get.lst \
tx_queue_prioritize.lst \
tx_queue_receive.lst \
tx_queue_send.lst \
tx_queue_send_notify.lst \
tx_semaphore_ceiling_put.lst \
tx_semaphore_cleanup.lst \
tx_semaphore_create.lst \
tx_semaphore_delete.lst \
tx_semaphore_get.lst \
tx_semaphore_info_get.lst \
tx_semaphore_initialize.lst \
tx_semaphore_performance_info_get.lst \
tx_semaphore_performance_system_info_get.lst \
tx_semaphore_prioritize.lst \
tx_semaphore_put.lst \
tx_semaphore_put_notify.lst \
tx_thread_create.lst \
tx_thread_delete.lst \
tx_thread_entry_exit_notify.lst \
tx_thread_identify.lst \
tx_thread_info_get.lst \
tx_thread_initialize.lst \
tx_thread_performance_info_get.lst \
tx_thread_performance_system_info_get.lst \
tx_thread_preemption_change.lst \
tx_thread_priority_change.lst \
tx_thread_relinquish.lst \
tx_thread_reset.lst \
tx_thread_resume.lst \
tx_thread_shell_entry.lst \
tx_thread_sleep.lst \
tx_thread_stack_analyze.lst \
tx_thread_stack_error_handler.lst \
tx_thread_stack_error_notify.lst \
tx_thread_suspend.lst \
tx_thread_system_preempt_check.lst \
tx_thread_system_resume.lst \
tx_thread_system_suspend.lst \
tx_thread_terminate.lst \
tx_thread_time_slice.lst \
tx_thread_time_slice_change.lst \
tx_thread_timeout.lst \
tx_thread_wait_abort.lst \
tx_time_get.lst \
tx_time_set.lst \
tx_timer_activate.lst \
tx_timer_change.lst \
tx_timer_create.lst \
tx_timer_deactivate.lst \
tx_timer_delete.lst \
tx_timer_expiration_process.lst \
tx_timer_info_get.lst \
tx_timer_initialize.lst \
tx_timer_performance_info_get.lst \
tx_timer_performance_system_info_get.lst \
tx_timer_system_activate.lst \
tx_timer_system_deactivate.lst \
tx_timer_thread_entry.lst \
tx_trace_buffer_full_notify.lst \
tx_trace_disable.lst \
tx_trace_enable.lst \
tx_trace_event_filter.lst \
tx_trace_event_unfilter.lst \
tx_trace_initialize.lst \
tx_trace_interrupt_control.lst \
tx_trace_isr_enter_insert.lst \
tx_trace_isr_exit_insert.lst \
tx_trace_object_register.lst \
tx_trace_object_unregister.lst \
tx_trace_user_event_insert.lst \
txe_block_allocate.lst \
txe_block_pool_create.lst \
txe_block_pool_delete.lst \
txe_block_pool_info_get.lst \
txe_block_pool_prioritize.lst \
txe_block_release.lst \
txe_byte_allocate.lst \
txe_byte_pool_create.lst \
txe_byte_pool_delete.lst \
txe_byte_pool_info_get.lst \
txe_byte_pool_prioritize.lst \
txe_byte_release.lst \
txe_event_flags_create.lst \
txe_event_flags_delete.lst \
txe_event_flags_get.lst \
txe_event_flags_info_get.lst \
txe_event_flags_set.lst \
txe_event_flags_set_notify.lst \
txe_mutex_create.lst \
txe_mutex_delete.lst \
txe_mutex_get.lst \
txe_mutex_info_get.lst \
txe_mutex_prioritize.lst \
txe_mutex_put.lst \
txe_queue_create.lst \
txe_queue_delete.lst \
txe_queue_flush.lst \
txe_queue_front_send.lst \
txe_queue_info_get.lst \
txe_queue_prioritize.lst \
txe_queue_receive.lst \
txe_queue_send.lst \
txe_queue_send_notify.lst \
txe_semaphore_ceiling_put.lst \
txe_semaphore_create.lst \
txe_semaphore_delete.lst \
txe_semaphore_get.lst \
txe_semaphore_info_get.lst \
txe_semaphore_prioritize.lst \
txe_semaphore_put.lst \
txe_semaphore_put_notify.lst \
txe_thread_create.lst \
txe_thread_delete.lst \
txe_thread_entry_exit_notify.lst \
txe_thread_info_get.lst \
txe_thread_preemption_change.lst \
txe_thread_priority_change.lst \
txe_thread_relinquish.lst \
txe_thread_reset.lst \
txe_thread_resume.lst \
txe_thread_suspend.lst \
txe_thread_terminate.lst \
txe_thread_time_slice_change.lst \
txe_thread_wait_abort.lst \
txe_timer_activate.lst \
txe_timer_change.lst \
txe_timer_create.lst \
txe_timer_deactivate.lst \
txe_timer_delete.lst \
txe_timer_info_get.lst 

C_DEPS += \
./rza/microsoft/azure-rtos/threadx/common/src/tx_block_allocate.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_block_pool_cleanup.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_block_pool_create.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_block_pool_delete.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_block_pool_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_block_pool_initialize.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_block_pool_performance_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_block_pool_performance_system_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_block_pool_prioritize.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_block_release.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_byte_allocate.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_cleanup.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_create.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_delete.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_initialize.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_performance_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_performance_system_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_prioritize.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_search.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_byte_release.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_event_flags_cleanup.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_event_flags_create.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_event_flags_delete.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_event_flags_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_event_flags_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_event_flags_initialize.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_event_flags_performance_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_event_flags_performance_system_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_event_flags_set.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_event_flags_set_notify.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_initialize_high_level.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_initialize_kernel_enter.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_initialize_kernel_setup.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_cleanup.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_create.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_delete.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_initialize.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_performance_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_performance_system_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_prioritize.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_priority_change.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_put.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_queue_cleanup.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_queue_create.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_queue_delete.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_queue_flush.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_queue_front_send.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_queue_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_queue_initialize.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_queue_performance_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_queue_performance_system_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_queue_prioritize.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_queue_receive.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_queue_send.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_queue_send_notify.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_ceiling_put.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_cleanup.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_create.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_delete.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_initialize.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_performance_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_performance_system_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_prioritize.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_put.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_put_notify.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_create.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_delete.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_entry_exit_notify.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_identify.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_initialize.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_performance_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_performance_system_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_preemption_change.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_priority_change.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_relinquish.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_reset.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_resume.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_shell_entry.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_sleep.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_stack_analyze.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_stack_error_handler.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_stack_error_notify.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_suspend.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_system_preempt_check.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_system_resume.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_system_suspend.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_terminate.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_time_slice.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_time_slice_change.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_timeout.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_wait_abort.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_time_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_time_set.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_timer_activate.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_timer_change.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_timer_create.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_timer_deactivate.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_timer_delete.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_timer_expiration_process.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_timer_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_timer_initialize.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_timer_performance_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_timer_performance_system_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_timer_system_activate.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_timer_system_deactivate.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_timer_thread_entry.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_trace_buffer_full_notify.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_trace_disable.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_trace_enable.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_trace_event_filter.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_trace_event_unfilter.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_trace_initialize.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_trace_interrupt_control.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_trace_isr_enter_insert.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_trace_isr_exit_insert.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_trace_object_register.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_trace_object_unregister.d \
./rza/microsoft/azure-rtos/threadx/common/src/tx_trace_user_event_insert.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_block_allocate.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_block_pool_create.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_block_pool_delete.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_block_pool_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_block_pool_prioritize.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_block_release.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_byte_allocate.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_byte_pool_create.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_byte_pool_delete.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_byte_pool_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_byte_pool_prioritize.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_byte_release.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_event_flags_create.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_event_flags_delete.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_event_flags_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_event_flags_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_event_flags_set.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_event_flags_set_notify.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_mutex_create.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_mutex_delete.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_mutex_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_mutex_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_mutex_prioritize.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_mutex_put.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_queue_create.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_queue_delete.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_queue_flush.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_queue_front_send.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_queue_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_queue_prioritize.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_queue_receive.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_queue_send.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_queue_send_notify.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_semaphore_ceiling_put.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_semaphore_create.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_semaphore_delete.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_semaphore_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_semaphore_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_semaphore_prioritize.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_semaphore_put.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_semaphore_put_notify.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_thread_create.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_thread_delete.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_thread_entry_exit_notify.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_thread_info_get.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_thread_preemption_change.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_thread_priority_change.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_thread_relinquish.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_thread_reset.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_thread_resume.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_thread_suspend.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_thread_terminate.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_thread_time_slice_change.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_thread_wait_abort.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_timer_activate.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_timer_change.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_timer_create.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_timer_deactivate.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_timer_delete.d \
./rza/microsoft/azure-rtos/threadx/common/src/txe_timer_info_get.d 

OBJS += \
./rza/microsoft/azure-rtos/threadx/common/src/tx_block_allocate.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_block_pool_cleanup.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_block_pool_create.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_block_pool_delete.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_block_pool_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_block_pool_initialize.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_block_pool_performance_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_block_pool_performance_system_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_block_pool_prioritize.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_block_release.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_byte_allocate.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_cleanup.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_create.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_delete.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_initialize.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_performance_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_performance_system_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_prioritize.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_byte_pool_search.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_byte_release.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_event_flags_cleanup.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_event_flags_create.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_event_flags_delete.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_event_flags_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_event_flags_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_event_flags_initialize.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_event_flags_performance_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_event_flags_performance_system_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_event_flags_set.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_event_flags_set_notify.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_initialize_high_level.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_initialize_kernel_enter.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_initialize_kernel_setup.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_cleanup.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_create.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_delete.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_initialize.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_performance_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_performance_system_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_prioritize.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_priority_change.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_mutex_put.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_queue_cleanup.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_queue_create.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_queue_delete.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_queue_flush.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_queue_front_send.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_queue_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_queue_initialize.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_queue_performance_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_queue_performance_system_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_queue_prioritize.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_queue_receive.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_queue_send.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_queue_send_notify.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_ceiling_put.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_cleanup.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_create.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_delete.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_initialize.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_performance_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_performance_system_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_prioritize.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_put.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_semaphore_put_notify.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_create.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_delete.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_entry_exit_notify.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_identify.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_initialize.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_performance_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_performance_system_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_preemption_change.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_priority_change.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_relinquish.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_reset.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_resume.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_shell_entry.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_sleep.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_stack_analyze.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_stack_error_handler.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_stack_error_notify.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_suspend.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_system_preempt_check.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_system_resume.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_system_suspend.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_terminate.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_time_slice.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_time_slice_change.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_timeout.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_thread_wait_abort.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_time_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_time_set.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_timer_activate.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_timer_change.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_timer_create.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_timer_deactivate.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_timer_delete.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_timer_expiration_process.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_timer_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_timer_initialize.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_timer_performance_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_timer_performance_system_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_timer_system_activate.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_timer_system_deactivate.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_timer_thread_entry.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_trace_buffer_full_notify.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_trace_disable.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_trace_enable.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_trace_event_filter.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_trace_event_unfilter.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_trace_initialize.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_trace_interrupt_control.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_trace_isr_enter_insert.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_trace_isr_exit_insert.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_trace_object_register.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_trace_object_unregister.o \
./rza/microsoft/azure-rtos/threadx/common/src/tx_trace_user_event_insert.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_block_allocate.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_block_pool_create.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_block_pool_delete.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_block_pool_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_block_pool_prioritize.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_block_release.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_byte_allocate.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_byte_pool_create.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_byte_pool_delete.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_byte_pool_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_byte_pool_prioritize.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_byte_release.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_event_flags_create.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_event_flags_delete.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_event_flags_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_event_flags_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_event_flags_set.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_event_flags_set_notify.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_mutex_create.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_mutex_delete.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_mutex_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_mutex_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_mutex_prioritize.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_mutex_put.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_queue_create.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_queue_delete.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_queue_flush.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_queue_front_send.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_queue_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_queue_prioritize.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_queue_receive.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_queue_send.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_queue_send_notify.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_semaphore_ceiling_put.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_semaphore_create.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_semaphore_delete.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_semaphore_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_semaphore_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_semaphore_prioritize.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_semaphore_put.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_semaphore_put_notify.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_thread_create.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_thread_delete.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_thread_entry_exit_notify.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_thread_info_get.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_thread_preemption_change.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_thread_priority_change.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_thread_relinquish.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_thread_reset.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_thread_resume.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_thread_suspend.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_thread_terminate.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_thread_time_slice_change.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_thread_wait_abort.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_timer_activate.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_timer_change.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_timer_create.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_timer_deactivate.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_timer_delete.o \
./rza/microsoft/azure-rtos/threadx/common/src/txe_timer_info_get.o 

MAP += \
tcp_mpu_test.map 


# Each subdirectory must supply rules for building sources it contributes
rza/microsoft/azure-rtos/threadx/common/src/%.o: ../rza/microsoft/azure-rtos/threadx/common/src/%.c
	@echo 'Building file: $<'
	$(file > $@.in,-mcpu=generic+simd -mcmodel=small -mcmodel=large -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-strict-aliasing -Wunused -Wuninitialized -Wall -Wextra -Wmissing-declarations -Wconversion -Wpointer-arith -Wshadow -Wlogical-op -Waggregate-return -Wfloat-equal -g -D_RENESAS_RZA_ -D_RZA_CORE=CA55_0 -D_RZA_ORDINAL=1 -I"C:\\Users\\erik\\e2_studio\\workspace\\tcp_mpu_test\\src" -I"." -I"C:\\Users\\erik\\e2_studio\\workspace\\tcp_mpu_test\\rza\\fsp\\inc" -I"C:\\Users\\erik\\e2_studio\\workspace\\tcp_mpu_test\\rza\\fsp\\inc\\api" -I"C:\\Users\\erik\\e2_studio\\workspace\\tcp_mpu_test\\rza\\fsp\\inc\\instances" -I"C:\\Users\\erik\\e2_studio\\workspace\\tcp_mpu_test\\rza\\fsp\\src\\rm_threadx_port" -I"C:\\Users\\erik\\e2_studio\\workspace\\tcp_mpu_test\\rza\\microsoft\\azure-rtos\\threadx\\common\\inc" -I"C:\\Users\\erik\\e2_studio\\workspace\\tcp_mpu_test\\rza\\fsp\\src\\bsp\\mcu\\rza3ul" -I"C:\\Users\\erik\\e2_studio\\workspace\\tcp_mpu_test\\rza_gen" -I"C:\\Users\\erik\\e2_studio\\workspace\\tcp_mpu_test\\rza_cfg\\fsp_cfg\\bsp" -I"C:\\Users\\erik\\e2_studio\\workspace\\tcp_mpu_test\\rza_cfg\\fsp_cfg" -I"C:\\Users\\erik\\e2_studio\\workspace\\tcp_mpu_test\\rza_cfg\\fsp_cfg\\azure\\tx" -I"C:\\Users\\erik\\e2_studio\\workspace\\tcp_mpu_test\\rza\\microsoft\\azure-rtos\\netxduo\\addons\\pop3" -I"C:\\Users\\erik\\e2_studio\\workspace\\tcp_mpu_test\\rza\\microsoft\\azure-rtos\\netxduo\\addons\\snmp" -I"C:\\Users\\erik\\e2_studio\\workspace\\tcp_mpu_test\\rza\\microsoft\\azure-rtos\\netxduo\\addons\\nat" -I"C:\\Users\\erik\\e2_studio\\workspace\\tcp_mpu_test\\rza\\microsoft\\azure-rtos\\netxduo\\addons\\mqtt" -I"C:\\Users\\erik\\e2_studio\\workspace\\tcp_mpu_test\\rza\\microsoft\\azure-rtos\\netxduo\\addons\\ftp" -I"C:\\Users\\erik\\e2_studio\\workspace\\tcp_mpu_test\\rza\\microsoft\\azure-rtos\\netxduo\\addons\\tftp" -I"C:\\Users\\erik\\e2_studio\\workspace\\tcp_mpu_test\\rza\\microsoft\\azure-rtos\\netxduo\\addons\\sntp" -I"C:\\Users\\erik\\e2_studio\\workspace\\tcp_mpu_test\\rza\\microsoft\\azure-rtos\\netxduo\\addons\\smtp" -I"C:\\Users\\erik\\e2_studio\\workspace\\tcp_mpu_test\\rza\\microsoft\\azure-rtos\\netxduo\\addons\\web" -I"C:\\Users\\erik\\e2_studio\\workspace\\tcp_mpu_test\\rza\\microsoft\\azure-rtos\\netxduo\\addons\\auto_ip" -I"C:\\Users\\erik\\e2_studio\\workspace\\tcp_mpu_test\\rza\\microsoft\\azure-rtos\\netxduo\\addons\\telnet" -I"C:\\Users\\erik\\e2_studio\\workspace\\tcp_mpu_test\\rza\\microsoft\\azure-rtos\\netxduo\\addons\\dns" -I"C:\\Users\\erik\\e2_studio\\workspace\\tcp_mpu_test\\rza\\microsoft\\azure-rtos\\netxduo\\addons\\dhcp" -I"C:\\Users\\erik\\e2_studio\\workspace\\tcp_mpu_test\\rza\\microsoft\\azure-rtos\\netxduo\\addons\\http" -I"C:\\Users\\erik\\e2_studio\\workspace\\tcp_mpu_test\\rza\\microsoft\\azure-rtos\\netxduo\\common\\inc" -I"C:\\Users\\erik\\e2_studio\\workspace\\tcp_mpu_test\\rza\\microsoft\\azure-rtos\\netxduo\\addons\\cloud" -I"C:\\Users\\erik\\e2_studio\\workspace\\tcp_mpu_test\\rza\\fsp\\src\\rm_netxduo_ether" -I"C:\\Users\\erik\\e2_studio\\workspace\\tcp_mpu_test\\rza_cfg\\fsp_cfg\\middleware" -I"C:\\Users\\erik\\e2_studio\\workspace\\tcp_mpu_test\\rza_cfg\\fsp_cfg\\azure\\nxd" -std=c99 -Wno-format-truncation -Wno-stringop-overflow --param=min-pagesize=0 -w -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<")
	@aarch64-none-elf-gcc @"$@.in"

