"<!DOCTYPE html>\r\n"
"<html lang=\"en\">\r\n"
"<head>\r\n"
"    <meta charset=\"UTF-8\">\r\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
"    <title>Document</title>\r\n"
"</head>\r\n"
"<body>\r\n"
"    <h1>Test Page</h1>\r\n"
"    <ul>\r\n"
"        <li>List item 1</li>\r\n"
"        <li>List item 2</li>\r\n"
"    </ul>\r\n"
"</body>\r\n"
"</html>\r\n"
